#!/bin/sh

# Copyright (c) 2019 John Franklin (jfranklin9000@gmail.com)
# Licensed under the MIT license.

if [ $# -ne 4 ]
then
	echo "usage: gh-branch <github-user> <github-repo> <source-branch-or-tag> <named-branch>"
	exit
fi

# Command line args.
usr=$1					# GITHUB-USER
rep=$2					# GITHUB-REPO
src=$3					# SOURCE-BRANCH (examples: master (branch), v0.4.4 (tag))
dst=$4					# NAMED-BRANCH (example: master, janitor, etc)

# We'll clone into this directory.
dir="$rep-$dst"

# This is where the everything lives.
URBIT="`echo ~/URBIT`"

# So go there.
if [ -d $URBIT ]
then
	echo "\nEntering $URBIT"
	cd $URBIT
else
	echo "$URBIT doesn't exist"
	exit
fi

# Create the branch if we can.
git clone -b $src $rep.git $dir
if [ $? -ne 0 ]
then
	exit
fi

# Configure the branch.
cd $dir

# Refer to URBIT-GIT-WORKFLOW.md for explanations of these commands.
git config --local branch.$src.rebase true
git remote add $usr https://github.com/$usr/$rep
git config --local remote.pushdefault $usr
git config --local remote.$usr.push +$src:$dst

echo "\nTo push this branch to GitHub execute these commands:"
echo "cd $URBIT/$dir"
echo "git push"
