#!/bin/sh

# Copyright (c) 2015 John Franklin (jfranklin9000@gmail.com)
# Licensed under the MIT license.

if [ $# -ne 3 ]
then
	echo "usage: jf9branch <github-user> <source-branch-or-tag> <named-branch>"
	exit
fi

# Command line args.
usr=$1					# GITHUB-USER
src=$2					# SOURCE-BRANCH (examples: master (branch), v0.4.4 (tag))
dst=$3					# NAMED-BRANCH (example: nock-decrement-opcode)

# We'll clone into this directory.
dir="urbit-$dst"

# This is where the everything lives.
URBIT="`echo ~/URBIT`"

# So go there.
if [ -d $URBIT ]
then
	echo "\nEntering $URBIT"
	cd $URBIT
else
	echo "$URBIT doesn't exist"
	exit
fi

# Create the branch if we can.
git clone -b $src urbit-jfranklin9000-fork.git $dir
if [ $? -ne 0 ]
then
	exit
fi
