#!/bin/sh

# Copyright (c) 2019 John Franklin (jfranklin9000@gmail.com)
# Licensed under the MIT license.

if [ $# -ne 3 ]
then
	echo "usage: landbranch <github-user> <source-branch-or-tag> <named-branch>"
	exit
fi

# Command line args.
usr=$1					# GITHUB-USER
src=$2					# SOURCE-BRANCH (examples: master)
dst=$3					# NAMED-BRANCH (example: typos)

gh-branch $usr landscape $src $dst
