#!/bin/sh

# Copyright (c) 2015 John Franklin (jfranklin9000@gmail.com)
# Licensed under the MIT license.

if [ $# -ne 2 ]
then
	echo "usage: urbranch <github-user> <urbit-branch>"
	exit
fi

# Command line args.
ghuser=$1					# GITHUB-USER
branch=$2					# URBIT-BRANCH

# We'll clone into this directory.
branchdir="urbit-$branch"

# Source branch to clone from.
# Only 'master' and 'test' exist.
# If $branch is 'master' $src will be 'master',
# else $src will be 'test'.
if [ $branch = "master" ]
then
	src="master"
else
	src="test"
fi

# This is where the everything lives.
URBIT="`echo ~/URBIT`"

# So go there.
if [ -d $URBIT ]
then
	echo "\nEntering $URBIT"
	cd $URBIT
else
	echo "$URBIT doesn't exist"
	exit
fi

# Create the branch if we can.
git clone -b $src urbit.git $branchdir
if [ $? -ne 0 ]
then
	exit
fi

# Configure the branch.
cd $branchdir

# Refer to URBIT-GIT-WORKFLOW.md for explanations of these commands.
git config --local branch.$src.rebase true
git remote add $ghuser https://github.com/$ghuser/urbit
git config --local remote.pushdefault $ghuser
git config --local remote.$ghuser.push +$src:$branch

echo "\nTo push this branch to GitHub execute these commands:"
echo "cd $URBIT/$branchdir"
echo "git push"
