#!/bin/sh

# Copyright (c) 2015 John Franklin (jfranklin9000@gmail.com)
# Licensed under the MIT license.

if [ $# -ne 3 ]
then
	echo "usage: urbranch <github-user> <source-branch-or-tag> <named-branch>"
	exit
fi

# Command line args.
usr=$1					# GITHUB-USER
src=$2					# SOURCE-BRANCH (examples: master (branch), v0.4.4 (tag))
dst=$3					# NAMED-BRANCH (example: nock-decrement-opcode)

gh-branch $usr urbit $src $dst
